2022-09-17 09:19:27,897 [INFO] D:\Django\Tack\assignment\performance\slowIterationCelery.py changed, reloading.
2022-09-17 09:19:46,212 [INFO] D:\Django\Tack\assignment\performance\slowIterationCelery.py changed, reloading.
2022-09-17 09:20:32,860 [INFO] D:\Django\Tack\assignment\performance\slowIterationCelery.py changed, reloading.
2022-09-17 09:22:27,966 [INFO] D:\Django\Tack\assignment\performance\slowIterationCelery.py changed, reloading.
2022-09-17 09:22:36,147 [INFO] Daily Prformance For Performance Object 1 Date 2022-09-16, Daily Revenue 1700.000
2022-09-17 09:22:36,210 [ERROR] Internal Server Error: /api/performance/slow_iteration/
Traceback (most recent call last):
  File "D:\Django\Tack\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Django\Tack\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Django\Tack\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Django\Tack\env\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Django\Tack\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\Django\Tack\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Django\Tack\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Django\Tack\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\Django\Tack\env\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "D:\Django\Tack\assignment\performance\views.py", line 33, in slow_iteration
    perfromSlowIteration()
  File "D:\Django\Tack\assignment\performance\slowIterationCelery.py", line 22, in perfromSlowIteration
    f.write(performance.id)
TypeError: write() argument must be str, not int
2022-09-17 09:22:54,758 [INFO] D:\Django\Tack\assignment\performance\slowIterationCelery.py changed, reloading.
2022-09-17 09:22:57,391 [INFO] Daily Prformance For Performance Object 1 Date 2022-09-16, Daily Revenue 1700.000
2022-09-17 09:24:55,969 [INFO] D:\Django\Tack\assignment\performance\slowIterationCelery.py changed, reloading.
2022-09-17 09:25:05,385 [INFO] Daily Prformance For Performance Object 1 Date 2022-09-16, Daily Revenue 1700.000
2022-09-17 09:25:12,086 [INFO] D:\Django\Tack\assignment\performance\views.py changed, reloading.
2022-09-17 09:31:51,572 [INFO] Daily Prformance For Performance Object 1 Date 2022-09-16, Daily Revenue 1700.000
2022-09-17 09:32:01,084 [INFO] D:\Django\Tack\assignment\performance\views.py changed, reloading.
2022-09-17 04:02:01,298 [INFO] Daily Prformance For Performance Object 1 Date 2022-09-16, Daily Revenue 1700.000
2022-09-17 04:02:04,572 [INFO] /mnt/d/Django/Tack/assignment/performance/views.py changed, reloading.
2022-09-17 04:50:00,237 [INFO] /mnt/d/Django/Tack/assignment/performance/urls.py changed, reloading.
2022-09-17 04:58:39,107 [ERROR] Internal Server Error: /api/performance/genertaeRandomData/
Traceback (most recent call last):
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: performance_dailyperformance.daily_revenue

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/d/Django/Tack/assignment/performance/views.py", line 39, in get
    insertRandomData()
  File "/mnt/d/Django/Tack/assignment/performance/slowIterationCelery.py", line 39, in insertRandomData
    DailyPerformance.objects.create(
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/models/base.py", line 831, in save
    self.save_base(
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/models/base.py", line 882, in save_base
    updated = self._save_table(
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/models/base.py", line 1025, in _save_table
    results = self._do_insert(
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/models/base.py", line 1066, in _do_insert
    return manager._insert(
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1657, in execute_sql
    cursor.execute(sql, params)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/mnt/d/Django/Tack/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: performance_dailyperformance.daily_revenue
2022-09-17 04:59:07,438 [INFO] /mnt/d/Django/Tack/assignment/performance/slowIterationCelery.py changed, reloading.
2022-09-17 05:01:42,539 [INFO] /mnt/d/Django/Tack/assignment/performance/views.py changed, reloading.
